### ISSUE TITLE
Toggle Button Not showing

### ISSUE THREAD

**Issue by MariposaTiff** [ryanpcmcquen/side_by_side_gdocs#2]
Hi, 

The toggle button does not show up for me. I have verified that my device is compatible. The S square button that shows up next to my Pinterest add on only takes me back to the chrome store. The Toggle button as shown in the screenshots on the chrome store next to the editing buttons do not show up in my docs. Please assist. Thank you.

**Comment by ryanpcmcquen** [comment]
What is your resolution? Is anything coming up in the JavaScript console?

**Comment by MariposaTiff** [comment]
Forgive me, but I don't know what a JavaScript console is.

**Comment by MariposaTiff** [comment]
I'm on a chromebook, by the way.

**Comment by ryanpcmcquen** [comment]
What is your screen resolution?

**Comment by ryanpcmcquen** [comment]
@MariposaTiff, what is your screen resolution?

**Comment by MariposaTiff** [comment]
1366 X 768

**Comment by ryanpcmcquen** [comment]
Hey @MariposaTiff, as noted in the README, your width resolution must be greater than 1632 for the button to appear:

https://github.com/ryanpcmcquen/side_by_side_gdocs#known-issues

**Comment by ryanpcmcquen** [comment]
@MariposaTiff, also note the previous discussion on this:

https://github.com/ryanpcmcquen/side_by_side_gdocs/issues/1

**Comment by MariposaTiff** [comment]
That's not even possible for my Chromebook. The highest possible is 1536 x
864. It would be nice to have something accessible for all of us, but since
that's not possible a disclaimer would be cool.

Thanks for your help anyway.

**Comment by ryanpcmcquen** [comment]
@MariposaTiff, as I noted in the other issue, it will not work in lower resolutions. I really did try to get it working, but there are some weird zoom settings that actually prevent two pages from appearing side-by-side within Google Docs. Hopefully Google will add a proper side-by-side view at some point, and I am betting that will work for all resolutions.

I also put a disclaimer on the README and on the description on the Chrome Web Store.

**Comment by MariposaTiff** [comment]
Ah ok. I totally missed it. I did see the notes about the editing. No
worries. It's still a cool feature for those who can use it. Hopefully
Google will get on board one day.

Thanks again.
